<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Dummy" Id="{f652e54c-ae20-4eed-8a72-16ac1274cc89}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Dummy
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Dummy">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>